// Korean, ko
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `탐색`,
	"Entries": `항목`,
	"Settings": `설정`,

	// Settings Page
	"Notifications": `알림`,
	"Prompt To Delete": `삭제할지 묻는 메시지`,
	"Show Running Balance": `러닝 잔액 표시`,
	"Allow notification": `알림 허용`,
	"Currency Symbol": `통화 기호`,
	"Appearance": `모양`,
	"Light": `밝은`,
	"Dark": `어둡게`,
	"Auto": `자동`,
	"Follow the preference of your device": `기기의 기본 설정을 따르세요.`,
	"Select Language": `언어 선택`,

	// Entries Page
	  "No entries yet. Add your first entry.": `  아직 항목이 없습니다. 첫 번째 항목을 추가하세요.`,
	"Balance": `잔액`,
	"Name": `이름`,
	"Amount": `금액`,

	// Delete Modal
	"Delete Entry": `항목 삭제`,
	"Are you sure you want to delete this entry?"
: `이 항목을 삭제하시겠습니까?`,
	"Cancel": `취소`,
	"Delete": `삭제`,
	"Entry deleted": `항목 삭제됨`,
}