// Portuguese, pt
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `Navegação`,
	"Entries": `Entradas`,
	"Settings": `Definições`,

	// Settings Page
	"Notifications": `Notificações`,
	"Prompt To Delete": `Pedir para apagar`,
	"Show Running Balance": `Mostrar saldo em curso`,
	"Allow notification": `Permitir notificação`,
	"Currency Symbol": `Símbolo da moeda`,
	"Appearance": `Aparência`,
	"Light": `Claro`,
	"Dark": `Escuro`,
	"Auto": `Automático`,
	"Follow the preference of your device": `Siga as preferências do seu dispositivo`,
	"Select Language": `Selecionar idioma`,

	// Entries Page
	  "No entries yet. Add your first entry.": `  Ainda não há registos. Adicione a sua primeira entrada.`,
	"Balance": `Balanço`,
	"Name": `Nome do utilizador`,
	"Amount": `Montante`,

	// Delete Modal
	"Delete Entry": `Eliminar registo`,
	"Are you sure you want to delete this entry?"
: `Tem a certeza de que pretende eliminar este registo?`,
	"Cancel": `Cancelar`,
	"Delete": `Apagar`,
	"Entry deleted": `Entrada eliminada`,
}