// German, de
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `Navigation`,
	"Entries": `Einträge`,
	"Settings": `Einstellungen`,

	// Settings Page
	"Notifications": `Benachrichtigungen`,
	"Prompt To Delete": `Zum Löschen auffordern`,
	"Show Running Balance": `Laufbilanz anzeigen`,
	"Allow notification": `Benachrichtigung zulassen`,
	"Currency Symbol": `Währungssymbol`,
	"Appearance": `Aussehen`,
	"Light": `Licht`,
	"Dark": `Dunkel`,
	"Auto": `Auto`,
	"Follow the preference of your device": `Befolgen Sie die Einstellungen Ihres Geräts`,
	"Select Language": `Wählen Sie Sprache aus`,
}