// German, de
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `Navigation`,
	"Entries": `Einträge`,
	"Settings": `Einstellungen`,

	// Settings Page
	"Notifications": `Benachrichtigungen`,
	"Prompt To Delete": `Zum Löschen auffordern`,
	"Show Running Balance": `Laufbilanz anzeigen`,
	"Allow notification": `Benachrichtigung zulassen`,
	"Currency Symbol": `Währungssymbol`,
	"Appearance": `Aussehen`,
	"Light": `Licht`,
	"Dark": `Dunkel`,
	"Auto": `Auto`,
	"Follow the preference of your device": `Befolgen Sie die Einstellungen Ihres Geräts`,
	"Select Language": `Wählen Sie Sprache aus`,

	// Entries Page
	  "No entries yet. Add your first entry.": `Aucune entrée pour l'instant. Ajoutez votre première entrée.`,
	"Balance": `Gleichgewicht`,
	"Name": `Name`,
	"Amount": `Menge`,

	// Delete Modal
	"Delete Entry": `Eintrag löschen`,
	"Are you sure you want to delete this entry?"
: `Sind Sie sicher, dass Sie diesen Eintrag löschen möchten?`,
	"Cancel": `Stornieren`,
	"Delete": `Löschen`,
	"Entry deleted": `Eintrag gelöscht`,
}