// Turkish, tr
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `Navigasyon`,
	"Entries": `Girişler`,
	"Settings": `Ayarlar`,

	// Settings Page
	"Notifications": `Bildirimler`,
	"Prompt To Delete": `Silme işlemi Onayı`,
	"Show Running Balance": `İşlem Bildirimi`,
	"Allow notification": `Bildirime izin ver`,
	"Currency Symbol": `Para Birimi Sembolü`,
	"Appearance": `Görünüm`,
	"Light": `Açık`,
	"Dark": `Koyu`,
	"Auto": `Otomatik`,
	"Follow the preference of your device": `Cihazınızın tercihini kullan`,
	"Select Language": `Dil Seçiniz`,
}