// Turkish, tr
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `Navigasyon`,
	"Entries": `Girişler`,
	"Settings": `Ayarlar`,

	// Settings Page
	"Notifications": `Bildirimler`,
	"Prompt To Delete": `Silme işlemi Onayı`,
	"Show Running Balance": `İşlem Bildirimi`,
	"Allow notification": `Bildirime izin ver`,
	"Currency Symbol": `Para Birimi Sembolü`,
	"Appearance": `Görünüm`,
	"Light": `Açık`,
	"Dark": `Koyu`,
	"Auto": `Otomatik`,
	"Follow the preference of your device": `Cihazınızın tercihini kullan`,
	"Select Language": `Dil Seçiniz`,

	// Entries Page
	  "No entries yet. Add your first entry.": `Henüz giriş yok. İlk girişinizi ekleyin.`,
	"Balance": `Tutar`,
	"Name": `İsim`,
	"Amount": `Miktar`,

	// Delete Modal
	"Delete Entry": `Girişi Sil`,
	"Are you sure you want to delete this entry?"
: `Bu girişi silmek istediğinizden emin misiniz?`,
	"Cancel": `İptal`,
	"Delete": `Sil`,
	"Entry deleted": `Giriş silindi`,
}