// This file was auto-generated by Quasalang

import enUS from './en-US'
import fr from './fr'
import de from './de'
import ru from './ru'
import it from './it'
import tr from './tr'

export default { 
	'en-US': enUS, // English
	'fr': fr, // French
	'de': de, // German
	'ru': ru, // Russian
	'it': it, // Italian
	'tr': tr, // Turkish
}