// Japanese, ja
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `ナビゲーション`,
	"Entries": `エントリー`,
	"Settings": `設定`,

	// Settings Page
	"Notifications": `通知`,
	"Prompt To Delete": `削除を促す`,
	"Show Running Balance": `残高表示`,
	"Allow notification": `通知を許可する`,
	"Currency Symbol": `通貨記号`,
	"Appearance": `外観`,
	"Light": `明るい`,
	"Dark": `暗い`,
	"Auto": `自動`,
	"Follow the preference of your device": `デバイスの好みに合わせる`,
	"Select Language": `言語を選択`,

	// Entries Page
	  "No entries yet. Add your first entry.": `  まだエントリがありません。最初のエントリーを追加してください。`,
	"Balance": `バランス`,
	"Name": `名前`,
	"Amount": `金額`,

	// Delete Modal
	"Delete Entry": `エントリーの削除`,
	"Are you sure you want to delete this entry?"
: `本当に削除しますか？`,
	"Cancel": `キャンセル`,
	"Delete": `削除`,
	"Entry deleted": `エントリー削除`,
}