// Hindi, hi
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `मार्गदर्शन`,
	"Entries": `प्रविष्टियां`,
	"Settings": `सेटिंग्स`,

	// Settings Page
	"Notifications": `सूचनाएं`,
	"Prompt To Delete": `हटाने का संकेत दें`,
	"Show Running Balance": `रनिंग बैलेंस दिखाएँ`,
	"Allow notification": `अधिसूचना की अनुमति दें`,
	"Currency Symbol": `मुद्रा चिह्न`,
	"Appearance": `उपस्थिति`,
	"Light": `रोशनी`,
	"Dark": `अँधेरा`,
	"Auto": `ऑटो`,
	"Follow the preference of your device": `अपने डिवाइस की प्राथमिकता का पालन करें`,
	"Select Language": `भाषा चुने`,

	// Entries Page
	  "No entries yet. Add your first entry.": `  अभी तक कोई प्रविष्टि नहीं. अपनी पहली प्रविष्टि जोड़ें.`,
	"Balance": `संतुलन`,
	"Name": `नाम`,
	"Amount": `मात्रा`,

	// Delete Modal
	"Delete Entry": `प्रविष्टि हटाएँ`,
	"Are you sure you want to delete this entry?"
: `क्या आप वाकई इस प्रविष्टि को हटाना चाहते हैं?`,
	"Cancel": `रद्द करना`,
	"Delete": `मिटाना`,
	"Entry deleted": `प्रविष्टि हटा दी गई`,
}