// English, en-US
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `Navigation`,
	"Entries": `Entries`,
	"Settings": `Settings`,

	// Settings Page
	"Notifications": `Notifications`,
	"Prompt To Delete": `Prompt To Delete`,
	"Show Running Balance": `Show Running Balance`,
	"Allow notification": `Allow notification`,
	"Currency Symbol": `Currency Symbol`,
	"Appearance": `Appearance`,
	"Light": `Light`,
	"Dark": `Dark`,
	"Auto": `Auto`,
	"Follow the preference of your device": `Follow the preference of your device`,
	"Select Language": `Select Language`,
}