// Spanish, es
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `Navegación`,
	"Entries": `Entradas`,
	"Settings": `Configuración`,

	// Settings Page
	"Notifications": `Notificaciones`,
	"Prompt To Delete": `Preguntar para borrar`,
	"Show Running Balance": `Mostrar saldo`,
	"Allow notification": `Permitir notificación`,
	"Currency Symbol": `Símbolo de moneda`,
	"Appearance": `Aspecto`,
	"Light": `Claro`,
	"Dark": `Oscuro`,
	"Auto": `Auto`,
	"Follow the preference of your device": `Siga las preferencias de su dispositivo`,
	"Select Language": `Seleccionar idioma`,

	// Entries Page
	  "No entries yet. Add your first entry.": `  Aún no hay entradas. Añade tu primera entrada.`,
	"Balance": `Saldo`,
	"Name": `Nombre`,
	"Amount": `Importe`,

	// Delete Modal
	"Delete Entry": `Borrar entrada`,
	"Are you sure you want to delete this entry?"
: `¿Está seguro de que desea eliminar esta entrada?`,
	"Cancel": `Cancelar`,
	"Delete": `Borrar`,
	"Entry deleted": `Entrada eliminada`,
}