// French, fr
// This file was auto-generated by Quasalang

export default {
  // Navbar
  Navigation: `Navigation`,
  Entries: `Entrées`,
  Settings: `Paramètres`,

  // Settings Page
  Notifications: `Notifications`,
  'Prompt To Delete': `Invite à supprimer`,
  'Show Running Balance': `Afficher le solde courant`,
  'Allow notification': `Autoriser les notifications`,
  'Currency Symbol': `Symbole monétaire`,
  Appearance: `Apparence`,
  Light: `Lumière`,
  Dark: `Sombre`,
  Auto: `Auto`,
  'Follow the preference of your device': `Suivez les préférences de votre appareil`,
  'Select Language': `Sélectionnez la langue`,

  // Entries Page
  'No entries yet. Add your first entry.': `Aucune entrée pour l'instant. Ajoutez votre première entrée.`,
  Balance: `équilibre`,
  Name: `Nom`,
  Amount: `Montant`,

  // Delete Modal
  'Delete Entry': `Supprimer l'entrée`,
  'Are you sure you want to delete this entry?': `Etes-vous sûr de vouloir supprimer cette entrée ?`,
  Cancel: `Annuler`,
  Delete: `Supprimer`,
  'Entry deleted': `Entrée supprimée`,
};
