// This file was auto-generated by Quasalang

import enUS from './en-US'
import tr from './tr'
import fr from './fr'
import de from './de'

export default { 
	'en-US': enUS, // English
	'tr': tr, // Turkish
	'fr': fr, // French
	'de': de, // German
}