// Chinese, zh
// This file was auto-generated by Quasalang

export default {

	// Navbar
	"Navigation": `导航`,
	"Entries": `条目`,
	"Settings": `设置`,

	// Settings Page
	"Notifications": `通知`,
	"Prompt To Delete": `提示删除`,
	"Show Running Balance": `显示运行余额`,
	"Allow notification": `允许通知`,
	"Currency Symbol": `货币符号`,
	"Appearance": `外观`,
	"Light": `浅色`,
	"Dark": `深色`,
	"Auto": `自动`,
	"Follow the preference of your device": `根据您设备的偏好`,
	"Select Language": `选择语言`,

	// Entries Page
	  "No entries yet. Add your first entry.": `  尚无条目。添加您的第一个条目。`,
	"Balance": `余额`,
	"Name": `姓名`,
	"Amount": `金额`,

	// Delete Modal
	"Delete Entry": `删除条目`,
	"Are you sure you want to delete this entry?"
: `您确定要删除此条目吗？`,
	"Cancel": `取消`,
	"Delete": `删除`,
	"Entry deleted": `已删除条目`,
}